dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y spatialite-bin libsqlite3-mod-spatialite
  - pip install poetry
install:
  - poetry install
script:
  - coverage run --source=geometry_to_spatialite ./run_tests.py
  - isort **/*.py -c --diff
  - flake8 .
  - black --check .
  - poetry build
after_success:
  - coveralls
