[tool.poetry]
name = "geometry-to-spatialite"
version = "0.3.2"
description = "Import geographic and spatial data from files into a SpatiaLite DB"
authors = ["chris48s"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/chris48s/geometry-to-spatialite"
homepage = "https://github.com/chris48s/geometry-to-spatialite"
documentation = "https://chris48s.github.io/geometry-to-spatialite"

[tool.poetry.dependencies]
python = "^3.6"
sqlite-utils = ">=2.1,<3.0"
Shapely = "^1.6.4"
pyshp = "^2.1.0"

[tool.poetry.dev-dependencies]
isort = "^5.6"
flake8 = "^3.8.4"
black = { version = "==20.8b1", allow-prereleases = true }
coveralls = "^2.1.2"
sphinx = "^3.2.1"
sphinx_rtd_theme = "^0.5.0"
myst-parser = "^0.12.10"
ghp-import = "^1.0.0"

[tool.poetry.scripts]
geojson-to-spatialite = 'geometry_to_spatialite.geojson:main'
shapefile-to-spatialite = 'geometry_to_spatialite.shapefile:main'
[build-system]
requires = ["poetry>=1.0.2"]
build-backend = "poetry.masonry.api"

