[tool.poetry]
name = "geometry-to-spatialite"
version = "0.3.2"
description = "Import geographic and spatial data from files into a SpatiaLite DB"
authors = ["chris48s"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/chris48s/geometry-to-spatialite"
homepage = "https://github.com/chris48s/geometry-to-spatialite"
documentation = "https://chris48s.github.io/geometry-to-spatialite"

[tool.poetry.dependencies]
python = "^3.6"
sqlite-utils = ">=2.1,<4.0"
Shapely = "^1.6.4"
pyshp = "^2.1.0"

[tool.poetry.dev-dependencies]
isort = "^5.8"
flake8 = "^3.9.1"
black = { version = "==20.8b1", allow-prereleases = true }
coverage = "^5.5"
sphinx = "^3.5.3"
sphinx_rtd_theme = "^0.5.1"
myst-parser = "^0.13.5"
ghp-import = "^1.1.0"

[tool.poetry.scripts]
geojson-to-spatialite = 'geometry_to_spatialite.geojson:main'
shapefile-to-spatialite = 'geometry_to_spatialite.shapefile:main'
[build-system]
requires = ["poetry>=1.0.2"]
build-backend = "poetry.masonry.api"
