name: Publish
on: create

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'tag'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system packages
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y spatialite-bin libsqlite3-mod-spatialite

      - name: Get python versions
        uses: chris48s/satisfying-python@main
        id: python-versions

      - name: Build, Test, Lint
        uses: chris48s/python-package-shared@main
        with:
          python-version: '${{ steps.python-versions.outputs.min }}'
          pre-install: flit

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist


  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'tag'
    permissions:
      contents: none
      id-token: write # required for trusted publishing
    environment: publish
    steps:
      - uses: actions/download-artifact@v3

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: artifact/
          print-hash: true
