name: Run tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system packages
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y spatialite-bin libsqlite3-mod-spatialite

      - name: 'Build, Test, Lint: ${{ matrix.python-version }}'
        uses: chris48s/python-package-shared@main
        with:
          python-version: ${{ matrix.python-version }}
          pre-install: flit
